name: Haskell with cabal no v2-

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # dirty hack applying ubuntu-18.04 (bionic) to execute xenial binaries
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc: '8.2.2'
            cabal-install: '2.0'           # hvr binary '2.0.0.1'
            cabal-option: --jobs=2
          - ghc: '8.0.2'
            cabal-install: '1.24'          # hvr binary '1.24.0.2'
            cabal-option: --jobs=2
          - ghc: '7.10.3'
            ghc-option: --ghc-option=-optl-no-pie
            cabal-install: '1.22'          # hvr binary '1.22.9.0'
            cabal-option: --jobs=2
          - ghc: '7.8.4'
            ghc-option: --ghc-option=-optl-no-pie
            cabal-install: '1.20'          # hvr binary '1.20.0.3' - test-command of 1.18 does not have ghc-option switch
          - ghc: '7.6.3'
            ghc-option: --ghc-option=-optl-no-pie
            cabal-install: '1.20'
          - ghc: '7.4.2'
            ghc-option: --ghc-option=-optl-no-pie
            cabal-install: '1.20'

    steps:
    - uses: actions/checkout@v2
    - uses: khibino/haskell-actions/setup@v1-g7
    # - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal-install }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Clear cabal configuration
      run: |
        # remove cabal configuration in cache
        rm ~/.cabal/config
        cabal --version
    - name: Install dependencies
      run: |
        set -ex
        opfile=CI/cabal-opts-${{ matrix.ghc }}
        opts="`[ ! -r $opfile ] || cat $opfile`"
        cabal update
        cabal install $opts ${{ matrix.ghc-option }} ${{ matrix.cabal-option }} --avoid-reinstalls --only-dependencies --enable-tests
    - name: Build
      run: |
        set -ex
        cabal configure --enable-tests
        cabal build ${{ matrix.ghc-option }} ${{ matrix.cabal-option }}
    - name: Run tests
      run: |
        set -ex
        # pass linker option for re-linking case
        cabal test ${{ matrix.ghc-option }}

### Local Variables: ***
### mode:yaml ***
### indent-tabs-mode: nil ***
### End: ***
